# Generated by Django 5.2.4 on 2025-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, verbose_name='usuario')),
                ('dream', models.TextField(verbose_name='sueño')),
                ('interpretation', models.TextField(verbose_name='interpretacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'interpretacion',
                'verbose_name_plural': 'interpretaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.CharField(max_length=100, verbose_name='descripcion')),
                ('value', models.TextField(verbose_name='valor')),
            ],
            options={
                'verbose_name': 'parametro',
                'verbose_name_plural': 'parametros',
            },
        ),
    ]
